alias sudo='sudo '
alias helpcommands="cat /home/pi/helpcommands"
alias shutdown='echo "not allowed"'
alias poweroff='echo "not allowed"'
alias halt='echo "not allowed"'
alias who='echo "kidding"'
alias ll='ls -lh'
alias l.='ls -lah'
alias extip="curl http://ipecho.net/plain; echo"
